// Mock data and constants for the Freelance Marketplace

import { Freelancer, Job } from '../types/marketplace';

// Filter options for job search
export const JOB_CATEGORIES = [
  'Web Development',
  'Data Science',
  'Design',
  'Writing',
  'Marketing',
  'Mobile Development',
  'DevOps',
];

export const PAY_RANGES = [
  { label: 'Any budget', value: 'any' },
  { label: '< $25/hr', value: '0-25' },
  { label: '$25–$50/hr', value: '25-50' },
  { label: '$50–$100/hr', value: '50-100' },
  { label: '> $100/hr', value: '100+' },
];

export const JOB_TYPES = ['Hourly', 'Fixed-price'];

export const LOCATIONS = ['Remote only', 'In-person', 'Hybrid'];

export const EXPERIENCE_LEVELS = ['Entry', 'Intermediate', 'Expert'];

// Mock freelancer data
export const MOCK_FREELANCERS: Freelancer[] = [
  {
    id: 1,
    name: 'Sarah Chen',
    title: 'Full-stack Developer',
    location: 'San Francisco, CA',
    description: 'Specialized in React, Node.js, and cloud architecture. 8+ years of experience building scalable web applications for startups and enterprises.',
    status: 'available',
    rating: 4.9,
    reviewCount: 127,
    jobsCompleted: 43,
    hourlyRate: 85,
    skills: ['React', 'Node.js', 'AWS'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 2,
    name: 'Marcus Johnson',
    title: 'UI/UX Designer',
    location: 'Austin, TX',
    description: 'Award-winning designer with a focus on creating delightful user experiences. Figma expert with a portfolio of 100+ successful projects.',
    status: 'limited',
    rating: 4.7,
    reviewCount: 89,
    jobsCompleted: 67,
    hourlyRate: 70,
    skills: ['Figma', 'UI Design', 'Prototyping'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 3,
    name: 'Emma Rodriguez',
    title: 'Data Scientist',
    location: 'New York, NY',
    description: 'PhD in Machine Learning. Helping businesses leverage data for strategic insights and predictions using cutting-edge AI techniques.',
    status: 'available',
    rating: 5.0,
    reviewCount: 156,
    jobsCompleted: 92,
    hourlyRate: 120,
    skills: ['Python', 'TensorFlow', 'SQL'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 4,
    name: 'Jake Thompson',
    title: 'Mobile Developer',
    location: 'Seattle, WA',
    description: 'Cross-platform mobile development specialist. Built 50+ apps with millions of downloads across iOS and Android platforms.',
    status: 'unavailable',
    rating: 4.3,
    reviewCount: 74,
    jobsCompleted: 38,
    hourlyRate: 65,
    skills: ['React Native', 'Swift', 'Kotlin'],
    isScamRisk: false,
    isVerified: false,
  },
  {
    id: 5,
    name: 'Quick Money LLC',
    title: 'Web Developer',
    location: 'Unknown',
    description: 'Fast and cheap web development services. We can do anything! Contact now for amazing deals!!! 100% satisfaction guaranteed!!!',
    status: 'available',
    rating: 3.2,
    reviewCount: 8,
    jobsCompleted: 2,
    hourlyRate: 15,
    skills: ['HTML', 'CSS', 'JavaScript'],
    isScamRisk: true,
    isVerified: false,
  },
  {
    id: 6,
    name: 'Olivia Park',
    title: 'Content Writer',
    location: 'Remote',
    description: 'Professional copywriter and content strategist. Specialized in SaaS, tech, and B2B content that converts visitors into customers.',
    status: 'available',
    rating: 4.8,
    reviewCount: 203,
    jobsCompleted: 187,
    hourlyRate: 55,
    skills: ['Copywriting', 'SEO', 'Content Strategy'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 7,
    name: 'David Kim',
    title: 'DevOps Engineer',
    location: 'Boston, MA',
    description: 'Infrastructure automation expert. Kubernetes, Docker, CI/CD pipelines, and cloud optimization specialist with enterprise experience.',
    status: 'limited',
    rating: 4.6,
    reviewCount: 91,
    jobsCompleted: 54,
    hourlyRate: 95,
    skills: ['Kubernetes', 'Docker', 'Terraform'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 8,
    name: 'Sophia Martinez',
    title: 'Brand Designer',
    location: 'Los Angeles, CA',
    description: 'Creative brand identity designer. Logo design, brand guidelines, and visual storytelling that makes your brand unforgettable.',
    status: 'available',
    rating: 4.9,
    reviewCount: 142,
    jobsCompleted: 78,
    hourlyRate: 75,
    skills: ['Branding', 'Illustrator', 'Logo Design'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 9,
    name: 'Alex Wei',
    title: 'Backend Engineer',
    location: 'Remote',
    description: 'Scalable backend systems architect specializing in microservices, APIs, and database optimization for high-traffic applications.',
    status: 'available',
    rating: 4.7,
    reviewCount: 112,
    jobsCompleted: 65,
    hourlyRate: 90,
    skills: ['Go', 'PostgreSQL', 'Redis'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 10,
    name: 'Priya Sharma',
    title: 'Product Manager',
    location: 'Chicago, IL',
    description: 'Technical product manager with 10+ years experience leading cross-functional teams to ship successful products from concept to launch.',
    status: 'limited',
    rating: 4.8,
    reviewCount: 95,
    jobsCompleted: 41,
    hourlyRate: 110,
    skills: ['Product Strategy', 'Agile', 'Analytics'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 11,
    name: 'Ryan O\'Connor',
    title: 'Video Editor',
    location: 'Miami, FL',
    description: 'Professional video editor and motion graphics designer. Creating engaging content for YouTube, social media, and corporate videos.',
    status: 'available',
    rating: 4.5,
    reviewCount: 78,
    jobsCompleted: 103,
    hourlyRate: 60,
    skills: ['After Effects', 'Premiere Pro', 'Motion Graphics'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 12,
    name: 'Cheap Coders Inc',
    title: 'Software Development',
    location: 'Offshore',
    description: 'Cheap offshore development! Any technology! Lowest prices guaranteed! Pay after delivery! No questions asked! Contact us now!!!',
    status: 'available',
    rating: 2.8,
    reviewCount: 12,
    jobsCompleted: 3,
    hourlyRate: 10,
    skills: ['Various'],
    isScamRisk: true,
    isVerified: false,
  },
  {
    id: 13,
    name: 'Nina Patel',
    title: 'QA Engineer',
    location: 'Denver, CO',
    description: 'Quality assurance specialist with expertise in automated testing, test strategy, and ensuring bug-free software releases.',
    status: 'available',
    rating: 4.6,
    reviewCount: 67,
    jobsCompleted: 52,
    hourlyRate: 70,
    skills: ['Selenium', 'Cypress', 'Test Automation'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 14,
    name: 'Carlos Mendez',
    title: 'Blockchain Developer',
    location: 'Remote',
    description: 'Smart contract developer and blockchain architect. Solidity expert with experience in DeFi and NFT projects.',
    status: 'limited',
    rating: 4.7,
    reviewCount: 45,
    jobsCompleted: 28,
    hourlyRate: 130,
    skills: ['Solidity', 'Web3', 'Ethereum'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 15,
    name: 'Jessica Lin',
    title: 'Technical Writer',
    location: 'Portland, OR',
    description: 'Creating clear, comprehensive technical documentation, API references, and developer guides that make complex concepts accessible.',
    status: 'available',
    rating: 4.8,
    reviewCount: 134,
    jobsCompleted: 156,
    hourlyRate: 65,
    skills: ['Documentation', 'API Docs', 'Markdown'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 16,
    name: 'Mohammed Al-Rashid',
    title: 'Security Engineer',
    location: 'Washington, DC',
    description: 'Cybersecurity expert specializing in penetration testing, security audits, and helping companies protect their digital assets.',
    status: 'unavailable',
    rating: 4.9,
    reviewCount: 88,
    jobsCompleted: 47,
    hourlyRate: 140,
    skills: ['Penetration Testing', 'Security Audit', 'OWASP'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 17,
    name: 'Amy Nguyen',
    title: 'SEO Specialist',
    location: 'Remote',
    description: 'Data-driven SEO strategist helping businesses improve organic search rankings and drive qualified traffic through proven tactics.',
    status: 'available',
    rating: 4.6,
    reviewCount: 101,
    jobsCompleted: 89,
    hourlyRate: 75,
    skills: ['SEO', 'Google Analytics', 'Keyword Research'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 18,
    name: 'Tyler Brooks',
    title: 'Game Developer',
    location: 'San Diego, CA',
    description: 'Indie game developer with experience in Unity and Unreal Engine. Published 12 games on Steam and mobile platforms.',
    status: 'limited',
    rating: 4.4,
    reviewCount: 56,
    jobsCompleted: 31,
    hourlyRate: 80,
    skills: ['Unity', 'C#', 'Game Design'],
    isScamRisk: false,
    isVerified: false,
  },
  {
    id: 19,
    name: 'Isabella Costa',
    title: 'Email Marketing Specialist',
    location: 'Atlanta, GA',
    description: 'Email marketing expert creating campaigns that convert. Specializing in e-commerce, SaaS, and B2B email strategies.',
    status: 'available',
    rating: 4.7,
    reviewCount: 93,
    jobsCompleted: 124,
    hourlyRate: 60,
    skills: ['Email Marketing', 'Mailchimp', 'A/B Testing'],
    isScamRisk: false,
    isVerified: true,
  },
  {
    id: 20,
    name: 'Ethan Brooks',
    title: '3D Artist',
    location: 'Remote',
    description: 'Professional 3D modeler and animator creating stunning visuals for games, films, and architectural visualization projects.',
    status: 'available',
    rating: 4.8,
    reviewCount: 72,
    jobsCompleted: 58,
    hourlyRate: 85,
    skills: ['Blender', '3D Modeling', 'Animation'],
    isScamRisk: false,
    isVerified: true,
  },
];

// Mock job data
export const MOCK_JOBS: Job[] = [
  {
    id: 1,
    title: 'Senior React Developer Needed',
    company: 'TechCorp',
    location: 'Remote',
    payType: 'hourly',
    payRate: 75,
    payMax: 100,
    postedDays: 2,
    description: 'Looking for an experienced React developer to help build our next-generation SaaS platform. Must have 5+ years of experience with modern React patterns, TypeScript, and state management.',
    skills: ['React', 'TypeScript', 'GraphQL'],
    applicants: 24,
    isVerified: true,
  },
  {
    id: 2,
    title: 'Mobile App UI/UX Design',
    company: 'StartupXYZ',
    location: 'Remote',
    payType: 'fixed',
    payRate: 3000,
    payMax: 5000,
    postedDays: 5,
    description: 'Need a talented designer to create mockups and prototypes for our fitness tracking mobile app. Looking for modern, clean design with excellent user flow.',
    skills: ['Figma', 'Mobile Design', 'Prototyping'],
    applicants: 47,
    isVerified: false,
  },
  {
    id: 3,
    title: 'Python Data Pipeline Developer',
    company: 'DataFlow Inc',
    location: 'Hybrid - SF Bay Area',
    payType: 'hourly',
    payRate: 85,
    payMax: 120,
    postedDays: 1,
    description: 'Build and maintain ETL pipelines for processing large datasets. Experience with Airflow and AWS required. Must be able to work with our team 2-3 days per week in San Francisco.',
    skills: ['Python', 'Airflow', 'AWS', 'SQL'],
    applicants: 12,
    isVerified: true,
  },
  {
    id: 4,
    title: 'Content Writer for Tech Blog',
    company: 'DevMedia',
    location: 'Remote',
    payType: 'fixed',
    payRate: 500,
    payMax: 800,
    postedDays: 3,
    description: 'Write 4-6 technical blog posts per month covering web development trends, tutorials, and best practices. Strong understanding of modern web technologies required.',
    skills: ['Technical Writing', 'SEO', 'Web Development'],
    applicants: 31,
    isVerified: true,
  },
  {
    id: 5,
    title: 'Full-stack Engineer (Node + React)',
    company: 'CloudSolutions',
    location: 'Remote',
    payType: 'hourly',
    payRate: 60,
    payMax: 90,
    postedDays: 7,
    description: 'Join our team to build internal tools and dashboards. Long-term contract opportunity with potential for full-time conversion. Must have experience with Node.js, React, and PostgreSQL.',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Docker'],
    applicants: 56,
    isVerified: false,
  },
  {
    id: 6,
    title: 'Brand Identity Design Package',
    company: 'GreenLeaf Co',
    location: 'Remote',
    payType: 'fixed',
    payRate: 2500,
    payMax: 4000,
    postedDays: 4,
    description: 'Looking for a designer to create a complete brand identity including logo, color palette, typography, and brand guidelines for our eco-friendly products company.',
    skills: ['Branding', 'Logo Design', 'Adobe Creative Suite'],
    applicants: 38,
    isVerified: true,
  },
  {
    id: 7,
    title: 'DevOps Engineer - Kubernetes',
    company: 'ScaleOps',
    location: 'Remote',
    payType: 'hourly',
    payRate: 90,
    payMax: 130,
    postedDays: 1,
    description: 'Help us migrate our infrastructure to Kubernetes. Need someone with strong experience in container orchestration, CI/CD, and cloud infrastructure.',
    skills: ['Kubernetes', 'Docker', 'AWS', 'CI/CD'],
    applicants: 18,
    isVerified: true,
  },
  {
    id: 8,
    title: 'WordPress Site Customization',
    company: 'Local Business Solutions',
    location: 'In-person - Pittsburgh, PA',
    payType: 'fixed',
    payRate: 1000,
    payMax: 1500,
    postedDays: 6,
    description: 'Customize our WordPress theme to match our brand. Need someone local who can meet in person for initial consultation. Basic PHP and WordPress knowledge required.',
    skills: ['WordPress', 'PHP', 'CSS'],
    applicants: 22,
    isVerified: false,
  },
  {
    id: 9,
    title: 'Machine Learning Engineer',
    company: 'AI Innovations',
    location: 'Remote',
    payType: 'hourly',
    payRate: 100,
    payMax: 150,
    postedDays: 2,
    description: 'Develop and deploy machine learning models for our recommendation system. Experience with Python, TensorFlow, and production ML systems essential.',
    skills: ['Python', 'TensorFlow', 'Machine Learning', 'MLOps'],
    applicants: 29,
    isVerified: true,
  },
  {
    id: 10,
    title: 'Social Media Manager',
    company: 'Fashion Forward',
    location: 'Hybrid - New York, NY',
    payType: 'hourly',
    payRate: 40,
    payMax: 60,
    postedDays: 5,
    description: 'Manage our Instagram, TikTok, and Pinterest accounts. Create engaging content and grow our follower base. Fashion industry experience preferred.',
    skills: ['Social Media', 'Content Creation', 'Instagram'],
    applicants: 67,
    isVerified: false,
  },
  {
    id: 11,
    title: 'iOS Developer for E-commerce App',
    company: 'ShopEasy',
    location: 'Remote',
    payType: 'hourly',
    payRate: 70,
    payMax: 95,
    postedDays: 3,
    description: 'Build new features for our iOS shopping app. Swift and SwiftUI experience required. Must be comfortable working with RESTful APIs and payment integrations.',
    skills: ['Swift', 'SwiftUI', 'iOS', 'Payment Integration'],
    applicants: 33,
    isVerified: true,
  },
  {
    id: 12,
    title: 'Video Editor for YouTube Channel',
    company: 'Tech Review Channel',
    location: 'Remote',
    payType: 'fixed',
    payRate: 150,
    payMax: 300,
    postedDays: 4,
    description: 'Edit 2-3 tech review videos per week. Looking for someone who can create engaging content with motion graphics and smooth transitions. Portfolio required.',
    skills: ['Premiere Pro', 'After Effects', 'Motion Graphics'],
    applicants: 41,
    isVerified: false,
  },
  {
    id: 13,
    title: 'Cybersecurity Audit',
    company: 'FinTech Secure',
    location: 'Remote',
    payType: 'fixed',
    payRate: 5000,
    payMax: 8000,
    postedDays: 1,
    description: 'Conduct comprehensive security audit of our financial platform. Must have experience with penetration testing and security compliance (SOC 2, ISO 27001).',
    skills: ['Penetration Testing', 'Security Audit', 'Compliance'],
    applicants: 9,
    isVerified: true,
  },
  {
    id: 14,
    title: 'SEO Optimization for E-commerce',
    company: 'Online Boutique',
    location: 'Remote',
    payType: 'hourly',
    payRate: 50,
    payMax: 75,
    postedDays: 8,
    description: 'Optimize our Shopify store for search engines. Need help with keyword research, on-page SEO, and content strategy to improve organic rankings.',
    skills: ['SEO', 'Shopify', 'Google Analytics'],
    applicants: 52,
    isVerified: false,
  },
  {
    id: 15,
    title: 'Unity Game Developer',
    company: 'Indie Game Studio',
    location: 'Remote',
    payType: 'hourly',
    payRate: 65,
    payMax: 85,
    postedDays: 6,
    description: 'Help us finish our indie puzzle game. Need someone with Unity experience and C# programming skills. Bonus if you have experience with mobile optimization.',
    skills: ['Unity', 'C#', 'Game Development'],
    applicants: 27,
    isVerified: false,
  },
  {
    id: 16,
    title: 'Technical Documentation Writer',
    company: 'API Platform',
    location: 'Remote',
    payType: 'fixed',
    payRate: 2000,
    payMax: 3500,
    postedDays: 2,
    description: 'Create comprehensive API documentation for our developer platform. Must have experience writing technical docs and understanding of RESTful APIs.',
    skills: ['Technical Writing', 'API Documentation', 'Markdown'],
    applicants: 19,
    isVerified: true,
  },
  {
    id: 17,
    title: 'Shopify Store Setup',
    company: 'New Retail Venture',
    location: 'Remote',
    payType: 'fixed',
    payRate: 1500,
    payMax: 2500,
    postedDays: 5,
    description: 'Set up complete Shopify store including theme customization, product import, payment setup, and shipping configuration. E-commerce experience required.',
    skills: ['Shopify', 'E-commerce', 'Liquid'],
    applicants: 44,
    isVerified: false,
  },
  {
    id: 18,
    title: '3D Character Artist',
    company: 'Animation Studio',
    location: 'Hybrid - Los Angeles, CA',
    payType: 'hourly',
    payRate: 75,
    payMax: 100,
    postedDays: 3,
    description: 'Create 3D character models and animations for our upcoming animated series. Blender or Maya experience required. Must be able to work on-site 2 days per week.',
    skills: ['Blender', '3D Modeling', 'Character Animation'],
    applicants: 31,
    isVerified: true,
  },
  {
    id: 19,
    title: 'Email Marketing Campaign',
    company: 'SaaS Startup',
    location: 'Remote',
    payType: 'fixed',
    payRate: 800,
    payMax: 1200,
    postedDays: 4,
    description: 'Design and implement a 6-email onboarding sequence for our SaaS product. Experience with email marketing tools and copywriting essential.',
    skills: ['Email Marketing', 'Copywriting', 'Mailchimp'],
    applicants: 36,
    isVerified: false,
  },
  {
    id: 20,
    title: 'Blockchain Smart Contract Development',
    company: 'DeFi Protocol',
    location: 'Remote',
    payType: 'hourly',
    payRate: 120,
    payMax: 180,
    postedDays: 1,
    description: 'Develop and audit smart contracts for our DeFi lending protocol. Solidity expert required with proven track record in secure contract development.',
    skills: ['Solidity', 'Smart Contracts', 'DeFi', 'Web3'],
    applicants: 14,
    isVerified: true,
  },
];
